name: t2v
channels:
  - defaults
dependencies:
  - python=3.11.2
  - pip=23.0.1
  - pip:
    - accelerate==0.18.0
    - opencv-python==4.7.0.72
    - streamlit==1.20.0
    - torch==2.0.0
    - git+https://github.com/huggingface/diffusers.git
    - git+https://github.com/huggingface/transformers.git
