name: ez-text2video
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pillow
  - torch
  - torchvision
  - pip:
    

git clone https://github.com/kpthedev/ez-text2video.git
cd ez-text2video
conda env create -f environment.yaml
